workspace = { members = ["wasm"] }
[package]
name = "wasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasi-common = "19.0.1"
wasmtime = "19.0.1"
